### ISSUE TITLE
mohon ukuran poto di bagian slide dan tubnailnya disesuaikan di tampilan PC maupun Mobile

### ISSUE THREAD

**Issue by sukrimalendra** [dikisiswanto/OpenSID-Cosmos#10]
ukuran poto pada slide dan tubnail tidak pas dengan potonya

![ukuran poto web1](https://user-images.githubusercontent.com/30992964/55344792-7c80dd80-54d8-11e9-9bf0-81e92a2849b3.PNG)

**Comment by dikisiswanto** [comment]
Terima kasih. gambar di bagian slider memang dibuat sama tinggi agar tetap *responsive*. konsekuensinya adalah gambar akan sedikit terpotong.

**Comment by sukrimalendra** [comment]
Mantab. Lanjutkan pak
