### ISSUE TITLE
error 500 pada link Arsip Artikel

### ISSUE THREAD

**Issue by balongbesuk** [dikisiswanto/OpenSID-Cosmos#11]
arsip artikel sepertinya ketinggalan jadi memunculkan error database 500

![weee5](https://user-images.githubusercontent.com/35319600/55351226-f2407580-54e7-11e9-9bae-463740930fab.jpg)

**Comment by dikisiswanto** [comment]
Terima kasih. Akan diperbaiki segera

**Comment by dikisiswanto** [comment]
Issue ini sudah coba diterapkan di website demo tema cosmos https://cosmos.celebiz.net/first . silakan diuji coba pak

**Comment by balongbesuk** [comment]
sip mas diki
