### ISSUE TITLE
Error dengan Widget Tambahan Sendiri

### ISSUE THREAD

**Issue by roaddee** [dikisiswanto/OpenSID-Cosmos#13]
Saya ada salah satu widget yang dibuat sendiri. dalam artian dibuat melalui siteman dengan menambahkan script sendiri. nah widget ini tidak muncul di halaman utama, tapi muncul di halaman berikutnya. pokoknya tidak mau muncul di halaman utama saja.
![err-diki1](https://user-images.githubusercontent.com/45786885/55374786-f4302600-5533-11e9-9e01-bd41a55e95fe.jpg)
![err-diki2](https://user-images.githubusercontent.com/45786885/55374793-fa260700-5533-11e9-9479-ff8398925186.jpg)

**Comment by dikisiswanto** [comment]
Ada contoh tampilan yang error?

**Comment by roaddee** [comment]
sdh sy edit issue nya (spt di post pertama)

**Comment by dikisiswanto** [comment]
widget mana yang dimaksud pak? apakah widget agenda?

**Comment by roaddee** [comment]
bukan widget rampak pintar itu, di kanan bawah. saya menggunakan tawk.to. cara pasangnya menggunakan tambah widget baru di administrasi web

**Comment by dikisiswanto** [comment]
Karena di tema ini, komponen widget tidak disertakan di halaman utama pak.

**Comment by roaddee** [comment]
oke kl begitu gpp. sy inject sendiri saja. krn ini widget tambahan saja.

**Comment by dikisiswanto** [comment]
Baik pak, issue ini saya tutup ya
