### ISSUE TITLE
script tertinggal?

### ISSUE THREAD

**Issue by balongbesuk** [dikisiswanto/OpenSID-Cosmos#14]
klik kanan > view page source 

![Untitled1](https://user-images.githubusercontent.com/35319600/55375976-7a4e6b80-5538-11e9-98f6-a1116d91fd7e.jpg)

**Comment by dikisiswanto** [comment]
Di laman yang mana?

**Comment by balongbesuk** [comment]
saya lihat website demo klik kanan > view page source

view-source:https://cosmos.celebiz.net/first

menggunakan firefox

**Comment by balongbesuk** [comment]
sepertinya bug firefox saya lihat di chrome tidak ada peringatan apa chrome tidak memiliki peringatan seperti firefox?, 

saya tutup saja karena rancu, saya sendiri tidak paham, :D
