### ISSUE TITLE
Data Statistik tidak tampil pada menu statis

### ISSUE THREAD

**Issue by arya096** [dikisiswanto/OpenSID-Cosmos#16]
Halo mas, saya baru mencoba menggunakan tema yang mas buat. namun ketika membuka menu statistik penduduk, data nya tidak tampil dan hanya menampilkan halaman kosong. apakah ada yg salah? atau ada settingan lain? mohon bantuan nya, terima kasih.
nb: saya menggunakan tema yg terbaru.
![Salah](https://user-images.githubusercontent.com/49260038/55525878-66844000-56c5-11e9-884c-546d8c5c67cb.PNG)

**Comment by dikisiswanto** [comment]
Lihat errornya di folder logs

**Comment by arya096** [comment]
ERROR - 2019-04-04 09:41:09 --> Severity: Parsing Error --> syntax error, unexpected '[' C:\xampp\htdocs\sidpds\themes\cosmos1.3\partials\statistik\statistik.php 164

Oh iya, ternyata kurangg " $ " . terima kasih bantuan nya mas.

![Statistik](https://user-images.githubusercontent.com/49260038/55526188-a13aa800-56c6-11e9-9ccd-1cf296bc2e59.PNG)

**Comment by dikisiswanto** [comment]
wah ternyata ada typo. terima kasih laporannya 👍
