### ISSUE TITLE
USUL untuk fungsi pencarian

### ISSUE THREAD

**Issue by balongbesuk** [dikisiswanto/OpenSID-Cosmos#17]
usul mas diki untuk fungsi pencarian usul saya cukup satu saja

![weee5](https://user-images.githubusercontent.com/35319600/55551800-d87c7980-5705-11e9-9b2a-fd1c8558f6be.jpg)

saya kira pencarian di sisi kanan (no 02) itu widget yang bisa dinonaktikan di aplikasi opensid ternyata bawaan thema, usul saya dihapus saja karena sudah ada pencarian di navbar (no 01),

**Comment by dikisiswanto** [comment]
Terima kasih, sudah diterapkan pada rilis baru dan bisa dilihat di website demo.

**Comment by balongbesuk** [comment]
terima kasih usulnya diterima
