### ISSUE TITLE
Mohon menu tampilan APBDES di buatkan menu input

### ISSUE THREAD

**Issue by sukrimalendra** [dikisiswanto/OpenSID-Cosmos#19]
Tema cosmos adalah tema yg super. Lebih super lagi menu input apbdesnya dibuatkan master diki

**Comment by dikisiswanto** [comment]
Fitur tersebut masih dikembangkan oleh OpenSID dan perlu diketahui bahwa tema cosmos hanya menangani masalah tampilan depannya saja.
