### ISSUE TITLE
Tidak bisa menampilkan web seperti yang diharapkan.

### ISSUE THREAD

**Issue by roaddee** [dikisiswanto/OpenSID-Cosmos#2]
![image](https://user-images.githubusercontent.com/45786885/55275205-4cd5a800-5315-11e9-8f4e-f30067d9ad50.png)

hasilnya seperti di atas ...

**Comment by dikisiswanto** [comment]
Coba screenshot tab console nya pak (Tekan F12). Ada error atau tidak.

**Comment by roaddee** [comment]
![image](https://user-images.githubusercontent.com/45786885/55275512-de471900-5319-11e9-9110-05d3403b2b57.png)

ada jquery

**Comment by dikisiswanto** [comment]
Pastikan file permissionnya sudah diatur pak agar bisa write and read. Karena sepertinya file CSS dan JS nya tidak termuat dengan baik

**Comment by roaddee** [comment]
saya kira kalau di lokal permission nya sudah full, apache selalu sudah full read/write di dalam folder xampp

**Comment by dikisiswanto** [comment]
Coba di view source (CTRL+U) pak, cek apakah link ke CSS nya mengarah dengan betul. Saya kurang tau masalahnya dimana karena di komputer saya oke oke saja

**Comment by roaddee** [comment]
link yang ke folder vendor salah semua mas, seharusnya localhost/opensid/desa/themes/cosmos/vendor, tpi kalau di halaman depan, terbaca localhost/desa/themes/cosmos/vendor

**Comment by dikisiswanto** [comment]
Harusnya ada error di console kalo ada file yang tidak termuat 🤔

**Comment by roaddee** [comment]
saya buat folder desa\themes di dalam folder htdocs. dan saya copy lagi folder cosmos. ternyata bisa. kalau saya lihat sepertinya $folder_themes itu hasilnya tidak sesuai yg diharapkan. krn opensid saya ada dlm folder opensid tidak di root

**Comment by dikisiswanto** [comment]
Bug ternyata ya pak. Oke saya fix dulu

**Comment by dikisiswanto** [comment]
Mohon bantuan testing pak.

**Comment by roaddee** [comment]
Oke. Apa sudah di fix ? Kl sudah mau saya test lagi

**Comment by dikisiswanto** [comment]
Silakan diuji coba pak. Rilis yang lama saya hapus
