### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by haqimkq** [dikisiswanto/OpenSID-Cosmos#20]
Bang mau nanya saya nyoba pakai cosmos knpa loading prosesx koq lama sekali y?

http://waninggap-miraf.educollege.web.id/index.php/first

**Comment by dikisiswanto** [comment]
Pastikan koneksi internet nya stabil dan cepat. Tema ini sudah dioptimasi dengan melakukan minified terhadap berkas CSS dan js

**Comment by sukrimalendra** [comment]
Saya coba buka lancar jaya
