### ISSUE TITLE
tes

### ISSUE THREAD

**Issue by ermansyahsopyan** [dikisiswanto/OpenSID-Cosmos#21]
mas diki kalo data anggaran ,APBDES,realisasi cara menampilkannya gimana ya?

**Comment by dikisiswanto** [comment]
Unduh rilis tema cosmos terbaru pak, edit manual di berkas partials/apdes.php

**Comment by ermansyahsopyan** [comment]
link cara edit nya ?

**Comment by dikisiswanto** [comment]
Edit nya sesuaikan dengan rincian anggarannya. Saat ini metode satu satunya ya harus edit berkas temanya langsung (file nya ada di folder partials dengan nama apdes.php) karena fitur unggah anggaran belum ada di OpenSID

**Comment by ermansyahsopyan** [comment]
mas diki mohon  maaf sekedar masukan untuk pendapatan mohon di tambahkan 
Dana Bantuan Keungan Kabupaten
Dana Bantuan Keuangan Provinsi
lain-lain pendapatan asli desa yang sah

dan untuk yang di realisasi mohon di tambahkan Penerimaan Pembiayaan
Terima Kasih

**Comment by dikisiswanto** [comment]
Tema ini bebas dikustomisasi pak, jadi bisa ditambahkan sendiri sesuai kebutuhan desa :)
