### ISSUE TITLE
tampilan gambar tidak bisa full di dalam konten

### ISSUE THREAD

**Issue by sukrimalendra** [dikisiswanto/OpenSID-Cosmos#22]
setelah saya amati mengapa gambar tidak bisa ditampilkan secara full karena kode **style** tidak dihasilkan oleh upload dari page editor konten.

**source kode** dari  https://cosmos.celebiz.net/first/artikel/101
![er2](https://user-images.githubusercontent.com/30992964/56108499-77ab3780-5f76-11e9-83b9-3d08165ce223.PNG)

![er3](https://user-images.githubusercontent.com/30992964/56108537-a1645e80-5f76-11e9-8017-a8d12920bcbe.PNG)

**source kode** dari page editor web openSID
![er1](https://user-images.githubusercontent.com/30992964/56108528-97daf680-5f76-11e9-9822-ba804c535b4c.PNG)

**Comment by dikisiswanto** [comment]
Diatur sendiri pak, di image properties (pada editor artikel), pilih tab advanced pada kotak style isikan width:100%; height:100%;

**Comment by sukrimalendra** [comment]
Ok. Terimakasih pak
