### ISSUE TITLE
Mas Diki gimana caranya menambah kan photo Kepala Daerah Sama Photo Kepala Desa Seperti Aparat Desa Yang sudah ada atau tolong di tambahkan menu Kepala Daerah Sama Kepala Desa 

### ISSUE THREAD

**Issue by ermansyahsopyan** [dikisiswanto/OpenSID-Cosmos#28]

**Comment by dikisiswanto** [comment]
Sila buka menu _Info Desa > Pemerintahan Desa_

**Comment by ermansyahsopyan** [comment]
klo terpisah bisa gak kan kepala daerah bukan aparatur desa

**Comment by dikisiswanto** [comment]
Bisa, tinggal edit judul widget nya menjadi kepala daerah, ada di menu _Admin Web > Widget_

**Comment by ermansyahsopyan** [comment]
editnya di cpanel apa di widgetnya langsung

**Comment by dikisiswanto** [comment]
Perlu edit langsung dari file widget, untuk mengganti

**Comment by dikisiswanto** [comment]
Issue ini saya tutup, jika ada pertanyaan silakan hubungi saya melalui telegram https://t.me/dikisiswanto
