### ISSUE TITLE
Usulan fungsi pencarian di home page awal

### ISSUE THREAD

**Issue by balongbesuk** [dikisiswanto/OpenSID-Cosmos#3]
awal saya buka Home Page nyari fungsi pencarian tidak ketemu mas diki, harus ke artikel dulu baru bisa menggunakan fungsi tersebut,

**Comment by dikisiswanto** [comment]
Baik, usulan ditampung. Akan dipertimbangkan untuk diterapkan pada versi berikutnya.

**Comment by dikisiswanto** [comment]
Usulan ini telah dikerjakan dan telah dicommit pada branch master. Silakan diujicoba agar bisa masuk ke rilis berikutnya
