### ISSUE TITLE
Perbaikan Widget Keuangan

### ISSUE THREAD

**Issue by WAHYUDIK** [dikisiswanto/OpenSID-Cosmos#31]
Dengan dirilisnya fitur keuangan di dasbhboard admin, dimana datanya akan ditampilkan di widget. sehingga perlu di perbaiki

**Comment by dikisiswanto** [comment]
Terima kasih. Perbaikan widget akan menyusul.

**Comment by dikisiswanto** [comment]
Sudah dikerjakan dan masuk di rilis terbaru
