### ISSUE TITLE
Redirect Lapor

### ISSUE THREAD

**Issue by RifkiCS29** [dikisiswanto/OpenSID-Cosmos#32]
Ketika Saya Sudah Login sebagai pendaftar layanan mandiri dan ingin membuat laporan, saya selalu redirect ke halaman login admin terlebih dahulu baru bisa membuat laporan.

**Comment by dikisiswanto** [comment]
Hal ini karena perubahan pada versi OpenSID terbaru belum diterapkan ke tema cosmos. Silakan gunakan tema bawaan dari OpenSID sambil menunggu tema cosmos diperbarui.
