### ISSUE TITLE
Unable to load the requested file: ../../themes/cosmos v140/template.php

### ISSUE THREAD

**Issue by mah-mudi** [dikisiswanto/OpenSID-Cosmos#33]
mohon solusi eror tersebut di opensid versi 19.11. 
offline lancar bisa diakses, tp ketika di online kan ke hosting, bisa masuk siteman tp ketika pemilihan tema ke cosmos mengalami kendala. eror unable...

**Comment by dikisiswanto** [comment]
Kesalahan ini terjadi karena Anda tidak menamai folder temanya dengan `cosmos`
