### ISSUE TITLE
Produk Hukum dan Informasi Publik Error

### ISSUE THREAD

**Issue by gampongbarabung** [dikisiswanto/OpenSID-Cosmos#35]
Mohon di perbaiki tampilan Produk Hukum dan Informasi Publik pada tema cosmos. mungkin permasalahan hanya pada Produk Hukum dan Informasi Publik yang tidak dapat dilihat outputnya

**Comment by dikisiswanto** [comment]
Sudah dikerjakan di rilis terbaru
