### ISSUE TITLE
Geser Tampilan Jadwal Sholat

### ISSUE THREAD

**Issue by roaddee** [dikisiswanto/OpenSID-Cosmos#37]
Tampilan jadwal sholat sudah cukup bagus, namun setelah dirasakan beberapa kali, mungkin letaknya perlu diperhatikan, karena berada di atas, mengakibatkan image/gambar slider yg ada objek berupa orang akan terhalangi oleh box/kotak jadwal sholat tersebut, apalagi kalau diakses dari HP akan mengakibatkan semua area image tertutupi oleh jadwal sholat.
Mungkin bisa dipertimbangkan letaknya di bawah, atau dimana saja agar tidak menutupi wajah.
**ini contoh gambar di PC :**
![2020-04-25_20h24_51](https://user-images.githubusercontent.com/45786885/80281105-11352980-8733-11ea-8341-83581f4be061.png)

**dan ini contoh gambar di HP**
![bomas-HP](https://user-images.githubusercontent.com/45786885/80281029-82c0a800-8732-11ea-8eec-c3976cd06f07.jpg)

**Comment by dikisiswanto** [comment]
Sudah masuk rilis terbaru. Terima kasih usulannya pak @roaddee
