### ISSUE TITLE
error 505

### ISSUE THREAD

**Issue by haqimkq** [dikisiswanto/OpenSID-Cosmos#4]
di upload ke hosting theme cosmos error

505
An Error Was Encountered
Unable to load the requested file: ../../themes/opensid-cosmos-1.1/template.php

**Comment by haqimkq** [comment]
https://waninggap-miraf.educollege.web.id/index.php/first

**Comment by dikisiswanto** [comment]
Apakah sudah mengikuti panduan instalasi? 

https://github.com/dikisiswanto/OpenSID-Cosmos/blob/master/README.md#instalasi

**Comment by haqimkq** [comment]
sudah bang,,

**Comment by haqimkq** [comment]
saya sudah cobain yg ver. 1.0 maupun 1.1

**Comment by dikisiswanto** [comment]
Gunakan rilis terbaru dan ikuti panduan, harusnya tidak ada masalah. Beberapa sudah menerapkan dan berhasil.

**Comment by haqimkq** [comment]
Kalau localhost aman bang,, tpi klo diterapkan dihosting error

**Comment by dikisiswanto** [comment]
Di panduan mengharuskan nama folder diubah menjadi `cosmos` apakah sudah diterapkan?

**Comment by haqimkq** [comment]
sudah bang,,

**Comment by haqi89** [comment]
kalau saya pakai theme hadakewa atau default berjalan normal

**Comment by dikisiswanto** [comment]
Saya cek web nya sudah berjalan normal

**Comment by haqimkq** [comment]
iya baru direfresh bang terimakasih

**Comment by haqimkq** [comment]
oy bang mw tanya kalau nama kepala desa sudah diupdate dan disave tapi pada saat cetak laporan nama masih yang lama editnya dimana y bang,,

**Comment by dikisiswanto** [comment]
Silakan baca panduan penggunaan OpenSID [https://github.com/opensid/opensid/wiki](https://github.com/opensid/opensid/wiki). Issue ini saya tutup.
