### ISSUE TITLE
Pengembangan Tema Cosmos

### ISSUE THREAD

**Issue by gampongbarabung** [dikisiswanto/OpenSID-Cosmos#40]
Mohon bisa ditambahakan fitur telah dibaca pada artikel yang telah diposting agar dapat diketahui jumlah artikel yang telah dibaca. Dan juga fitur yang mengetahui jumlah orang yang sedang melihat website kita. Mohon bantuannya pak diki

**Comment by dikisiswanto** [comment]
Fitur untuk menampilkan jumlah pembaca pada artikel sudah ditambahkan di rilis terbaru. Terima kasih

**Comment by gampongbarabung** [comment]
luar biasa pak diki terimakasih
