### ISSUE TITLE
Update Jumlah Covid-19 Provinsi

### ISSUE THREAD

**Issue by gampongbarabung** [dikisiswanto/OpenSID-Cosmos#42]
Setelah dilihat dibeberapa grafik jumlah covid - 19 di aceh total yang sembuh tidak diperbarui pada tgl 02 Mei 2020. Dimana Jumlah yang sembuh Pada Tanggal 02 Mei 2020 di Aceh sudah 8 Orang tetapi pada Website barabung.desa.id masih 4 Orang. Dan saya cek ke website http://pusatkrisis.kemkes.go.id/covid-19-id/ baru 6 Orang Yang sembuh pada Tanggal 02 Mei 2020. Sedangkan Pada Website https://covid19.acehprov.go.id/ Per Tanggal 02 Mei Jumlah Yang Sembuh sudah Mencapai 8 Orang. Apakah data belum diupdate ke Website atau ada kendala pada pengambilan data Covid-19? 

Berikut Gambarnya :
1. barabung.desa.id (Saya Screen Shot Tanggal 03 Mei 2020)

![barabungcovid](https://user-images.githubusercontent.com/60224596/80890921-d1e67a00-8cea-11ea-8668-e2125ef7d2fe.png)

2. http://pusatkrisis.kemkes.go.id/covid-19-id/ (Saya Screen Shot Tanggal 03 Mei 2020)

![pusatkrisiscovid](https://user-images.githubusercontent.com/60224596/80890932-e591e080-8cea-11ea-8b34-9b37a11d33e8.png)

3. https://covid19.acehprov.go.id/ (Saya Screen Shot Tanggal 03 Mei 2020)

![Covid Aceh](https://user-images.githubusercontent.com/60224596/80891006-7cf73380-8ceb-11ea-9d67-f58949be7263.png)

**Comment by dikisiswanto** [comment]
Datanya berasal dari API kawalcorona.com. Kemungkinan karena lambat diperbarui. Saya juga sudah cek di website kawalcorona.com datanya sama seperti yg ada di website desa Barabung

**Comment by gampongbarabung** [comment]
Baik pak . Saya kira diambil dari point nomor 2
