### ISSUE TITLE
Memunculkan Tombol Pada Foto Aparatur Desa

### ISSUE THREAD

**Issue by gampongbarabung** [dikisiswanto/OpenSID-Cosmos#47]
![81169671-6ab71700-8fc3-11ea-8100-110081ecc099](https://user-images.githubusercontent.com/60224596/81170083-3b54da00-8fc4-11ea-8aa3-f5e1408708f8.png)

Sekarang pada widget aparatur desa foto perangkat desanya pindah sendiri tetapi tidak bisa mundur kebelakang. Jika ada 10 perangkat desa, kita kelewatan melihat foto kepala desanya karna di no 1 biasanya kepala desa, untuk dapat melihatnya harus menunggu sampai ulang lagi ke foto no 1. Mungkin bisa dibuatkan tombol pindah kiri dan kanan Seperti pada gambar diatas yang sudah dikolom kuning.

**Comment by dikisiswanto** [comment]
Widget tersebut bawaan dari OpenSID. Jika dirasa perlu diperbaiki, silakan ajukan issue di repo OpenSID.

**Comment by gampongbarabung** [comment]
Baik terimakasih pak 👍
