### ISSUE TITLE
Error Di Opensid 20.05 Tidak Bisa Load template.php

### ISSUE THREAD

**Issue by teguhdwiprast** [dikisiswanto/OpenSID-Cosmos#49]
Keterangan Error:

 An Error Was Encountered
Unable to load the requested file: ../../desa/themes/cosmos/template.php

**Comment by dikisiswanto** [comment]
Silakan baca panduan

https://github.com/dikisiswanto/OpenSID-Cosmos/blob/master/README.md#instalasi

**Comment by teguhdwiprast** [comment]
Sepertinya sudah sesuai panduan

[https://nimb.ws/XzeSa7](url)
[https://nimb.ws/kIoxcO](url)

**Comment by teguhdwiprast** [comment]
Oke fix nama foldernya huruf kapital tadi saya ganti huruf kecil bisa.

terima kasih
