### ISSUE TITLE
Whatsapp social button tidak berfungsi

### ISSUE THREAD

**Issue by roaddee** [dikisiswanto/OpenSID-Cosmos#5]
1. Tombol Whatsapp tidak berfungsi ketika di klik
2. kalau bisa di setiap artikel diberi tombol untuk kembali ke halaman awal / homepage

**Comment by dikisiswanto** [comment]
Terima kasih. Akan diperbaiki di rilis berikutnya.

Untuk usulan nomor 2 peletakan tombol ada dimana?

**Comment by dikisiswanto** [comment]
Tombol ke laman utama/homepage ditambahkan pada bagian menu. Issue ini telah dikerjakan dan akan diterapkan pada rilis berikutnya
