### ISSUE TITLE
Menu Dropdown Tidak Berfungsi

### ISSUE THREAD

**Issue by ariandii** [dikisiswanto/OpenSID-Cosmos#62]
Pada halaman peta, menu dropdown tidak berfungsi seperti seharusnya.

![image](https://user-images.githubusercontent.com/46939846/89735192-f8a31200-da8a-11ea-86fe-6f0974e21527.png)

**Comment by RomziJazz** [comment]
![Screenshot_20200817-190608_Chrome](https://user-images.githubusercontent.com/65128302/90394688-4e943d00-e0bd-11ea-8fad-9be1b08885ba.png)
Tombol menu hanya bisa di klik pada text saja tidak full memanjang kesamping seperti selector home...
