### ISSUE TITLE
Sembunyikan Icon Sosial Media pada Footer yang tidak ber-Akun

### ISSUE THREAD

**Issue by ariandii** [dikisiswanto/OpenSID-Cosmos#65]
Jika username akun sosial media tidak tersedia, agar dapat disembunyikan icon bersangkutan sehingga tidak menghasilkan link default sosial media tersebut.

![image](https://user-images.githubusercontent.com/46939846/89735292-aa424300-da8b-11ea-9349-0020fb3f0896.png)

**Comment by dikisiswanto** [comment]
Terima kasih bung @ariandii sudah melaporkan. Sepertinya issue ini tidak berlaku. Sebab di versi beta sekarang, media sosial memang tidak ditampilkan jika tidak diisi.

**Comment by ariandii** [comment]
siap pak, sebab saya klik icon Youtube dan Instagram masih link utama, saya pikir itu blm diisi 😊
