### ISSUE TITLE
Cara menampilkan grafik pd data statistik perlu diperbaharui

### ISSUE THREAD

**Issue by andifahruddinakas** [dikisiswanto/OpenSID-Cosmos#67]
![Screenshot_2020-08-10-09-18-07-84.png](https://user-images.githubusercontent.com/57283157/89746105-21a2c180-dae2-11ea-8719-60d33dda2e1f.png)

Bisa cek codingn tema standar OpenSID

**Comment by dikisiswanto** [comment]
Apa yang berbeda ya bung @afa28?

**Comment by andifahruddinakas** [comment]
> Apa yang berbeda ya bung @afa28?

Cuma button pie dan grafik nya sj yg dijadikan 1 😆😆😆
