### ISSUE TITLE
cosmo 1.6.6 map tidak muncul

### ISSUE THREAD

**Issue by ReyhanArraaf** [dikisiswanto/OpenSID-Cosmos#69]
saya menemukan masalah saat saya mencoba menerapkan tema cosmo 1.6.6 , dimana map pada menu "peta" maupun pada widget tidak muncul. Padahal saya sudah setting lokasi map saya. Mohon bantuannya
![Screenshot_8](https://user-images.githubusercontent.com/58810252/104363373-aab59d00-5547-11eb-8781-abe2d819a0c5.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/58810252/104363403-b3a66e80-5547-11eb-9740-e9215c92f8b3.jpg)

**Comment by dikisiswanto** [comment]
cosmo v1.x.x tidak lagi didukung, gunakan v2.x.x

**Comment by ReyhanArraaf** [comment]
baik terimakasih banyak
