### ISSUE TITLE
Peta Desa di Website Baik Vesi Online maupun Offline tidak dapat ditampilkan

### ISSUE THREAD

**Issue by Zoel-WB** [dikisiswanto/OpenSID-Cosmos#71]
![image](https://user-images.githubusercontent.com/64481641/119248249-1aa0f780-bbba-11eb-951e-eada9826a8c2.png)

**Comment by dikisiswanto** [comment]
Sepertinya tidak kompatibel dengan versi premium. Saat ini baru diujicoba di reguler

**Comment by Zoel-WB** [comment]
Pantesan tidak bisa tampil saya fikir tadi karena ada tulisan Hak Cipta sehingga petanya tertutup..... oke Pak...
