### ISSUE TITLE
Tampilan Seluler tidak bekerja normal

### ISSUE THREAD

**Issue by sukrimalendra** [dikisiswanto/OpenSID-Cosmos#8]
Saya test menggunakan handpone (hp) untuk membuka web desa saya yang sudah saya instal theme cosmos. tetapi setelah saya check pada handpone (hp) tampilannya tetap padi loading muter-muter terus. akhirnya saya seting browser saya di hp dengan tampilan desktop baru web bisa dibuka. mohon untuk dicheck. terimakasih

**Comment by dikisiswanto** [comment]
Saya cek web nya http://www.pelangan.desa.id/first tidak ada masalah

**Comment by sukrimalendra** [comment]
Bapak bukanya dengan HP?

**Comment by dikisiswanto** [comment]
ya
