### ISSUE TITLE
mohon menambahkan tombol login ke siteman web opensid

### ISSUE THREAD

**Issue by sukrimalendra** [dikisiswanto/OpenSID-Cosmos#9]
jika mengakses web desa dengan tema cosmos saya merasa kewalahan jika tidak ada tombol login ke siteman web opensid desa. mohon perbaikannya. tetap semangat dan terimakasih banyak.

**Comment by dikisiswanto** [comment]
Issue ini sudah dikerjakan. Sila cek website demo tema cosmos https://cosmos.celebiz.net/first pada bagian footer untuk uji coba

**Comment by roaddee** [comment]
saya kira untuk login admin, khan bisa ditambah sendiri via siteman. tinggal kita tambah link sendiri dan langsung tampil

**Comment by sukrimalendra** [comment]
Terimakasih bapak
